setwd("/panfs/pfs.local/work/colella/ben/002.simulations/003.SecondaryContact_vs_IBD/03.conStruct/layerContributions/")

library(ggplot2) 
library(conStruct)
library(scales)
library(reshape2)

############################
#######     IBD    #########
############################

# Loop through output files generated by conStruct 

layer.contributions <- matrix(NA,nrow=2,ncol=1)

# load the conStruct.results.Robj and data.block.Robj
#   files saved at the end of a conStruct run
load("../IBD.gen.0_conStruct.results.Robj")
load("../IBD.gen.0_data.block.Robj")

# calculate layer contributions
layer.contributions[,1] <- calculate.layer.contribution(conStruct.results[[1]],data.block)
tmp <- conStruct.results[[1]]$MAP$admix.proportions

for(i in c(200,1000,10000,19000)){
  # load the conStruct.results.Robj and data.block.Robj
  #   files saved at the end of a conStruct run
  load(sprintf("../IBD.gen.%s_conStruct.results.Robj",i))
  load(sprintf("../IBD.gen.%s_data.block.Robj",i))
  
  # match layers up across runs to keep plotting colors consistent
  #   for the same layers in different runs
  tmp.order <- match.layers.x.runs(tmp,conStruct.results[[1]]$MAP$admix.proportions)  
  
  # calculate layer contributions
  layer.contributions <- cbind(layer.contributions, calculate.layer.contribution(conStruct.results=conStruct.results[[1]],
                                                            data.block=data.block,
                                                            layer.order=tmp.order))
  tmp <- conStruct.results[[1]]$MAP$admix.proportions[,tmp.order]
}



barplot(layer.contributions,
        col=c("red", "blue"),
        xlab="Generation",
        ylab="Layer Contributions",
        main="IBD",
        names.arg=c("0","200","1,000","10,000","19,000"))

dev.print(pdf, "IBD.layer.contributions.pdf")




############################
#######     SC     #########
############################

# Loop through output files generated by conStruct 

layer.contributions <- matrix(NA,nrow=2,ncol=1)

# load the conStruct.results.Robj and data.block.Robj
#   files saved at the end of a conStruct run
load("../Secondary_Contact.gen.0_conStruct.results.Robj")
load("../Secondary_Contact.gen.0_data.block.Robj")

# calculate layer contributions
layer.contributions[,1] <- calculate.layer.contribution(conStruct.results[[1]],data.block)
tmp <- conStruct.results[[1]]$MAP$admix.proportions

for(i in c(200,1000,10000,19000)){
  # load the conStruct.results.Robj and data.block.Robj
  #   files saved at the end of a conStruct run
  load(sprintf("../Secondary_Contact.gen.%s_conStruct.results.Robj",i))
  load(sprintf("../Secondary_Contact.gen.%s_data.block.Robj",i))
  
  # match layers up across runs to keep plotting colors consistent
  #   for the same layers in different runs
  tmp.order <- match.layers.x.runs(tmp,conStruct.results[[1]]$MAP$admix.proportions)  
  
  # calculate layer contributions
  layer.contributions <- cbind(layer.contributions, calculate.layer.contribution(conStruct.results=conStruct.results[[1]],
                                                                                 data.block=data.block,
                                                                                 layer.order=tmp.order))
  tmp <- conStruct.results[[1]]$MAP$admix.proportions[,tmp.order]
}



barplot(layer.contributions,
        col=c("red", "blue"),
        xlab="Generation",
        ylab="Layer Contributions",
        main="Secondary_Contact",
        names.arg=c("0","200","1,000","10,000","19,000"))

dev.print(pdf, "Secondary_Contact.layer.contributions.pdf")





############################
#######     TZ     #########
############################

# Loop through output files generated by conStruct 

layer.contributions <- matrix(NA,nrow=2,ncol=1)

# load the conStruct.results.Robj and data.block.Robj
#   files saved at the end of a conStruct run
load("../Tension_Zone.gen.0_conStruct.results.Robj")
load("../Tension_Zone.gen.0_data.block.Robj")

# calculate layer contributions
layer.contributions[,1] <- calculate.layer.contribution(conStruct.results[[1]],data.block)
tmp <- conStruct.results[[1]]$MAP$admix.proportions

for(i in c(200,1000,10000,19000)){
  # load the conStruct.results.Robj and data.block.Robj
  #   files saved at the end of a conStruct run
  load(sprintf("../Tension_Zone.gen.%s_conStruct.results.Robj",i))
  load(sprintf("../Tension_Zone.gen.%s_data.block.Robj",i))
  
  # match layers up across runs to keep plotting colors consistent
  #   for the same layers in different runs
  tmp.order <- match.layers.x.runs(tmp,conStruct.results[[1]]$MAP$admix.proportions)  
  
  # calculate layer contributions
  layer.contributions <- cbind(layer.contributions, calculate.layer.contribution(conStruct.results=conStruct.results[[1]],
                                                                                 data.block=data.block,
                                                                                 layer.order=tmp.order))
  tmp <- conStruct.results[[1]]$MAP$admix.proportions[,tmp.order]
}



barplot(layer.contributions,
        col=c("red", "blue"),
        xlab="Generation",
        ylab="Layer Contributions",
        main="Tension_Zone",
        names.arg=c("0","200","1,000","10,000","19,000"))

dev.print(pdf, "Tension_Zone.layer.contributions.pdf")




